import type { Location, Promotion } from "@/types/flight"

export const popularDestinations: Location[] = [
  { name: "Bogotá", code: "BOG", country: "Colombia" },
  { name: "Medellín", code: "MDE", country: "Colombia" },
  { name: "Cali", code: "CLO", country: "Colombia" },
  { name: "Cartagena", code: "CTG", country: "Colombia" },
  { name: "San Andrés", code: "ADZ", country: "Colombia" },
  { name: "Barranquilla", code: "BAQ", country: "Colombia" },
  { name: "Bucaramanga", code: "BGA", country: "Colombia" },
  { name: "Pereira", code: "PEI", country: "Colombia" },
  { name: "Armenia", code: "AXM", country: "Colombia" },
  { name: "Santa Marta", code: "SMR", country: "Colombia" },
  { name: "Arauca", code: "AUC", country: "Colombia" },
  { name: "Barrancabermeja", code: "EJA", country: "Colombia" },
  { name: "Cúcuta", code: "CUC", country: "Colombia" },
  { name: "Ibagué", code: "IBE", country: "Colombia" },
  { name: "Manizales", code: "MZL", country: "Colombia" },
  { name: "Montería", code: "MTR", country: "Colombia" },
  { name: "Neiva", code: "NVA", country: "Colombia" },
  { name: "Pasto", code: "PSO", country: "Colombia" },
  { name: "Popayán", code: "PPN", country: "Colombia" },
  { name: "Quibdó", code: "UIB", country: "Colombia" },
  { name: "Riohacha", code: "RCH", country: "Colombia" },
  { name: "Sincelejo", code: "CZU", country: "Colombia" },
  { name: "Valledupar", code: "VUP", country: "Colombia" },
  { name: "Villavicencio", code: "VVC", country: "Colombia" },
  { name: "Yopal", code: "EYP", country: "Colombia" },
  { name: "Leticia", code: "LET", country: "Colombia" },
  { name: "Florencia", code: "FLA", country: "Colombia" },
  { name: "Mitu", code: "MVP", country: "Colombia" },
  { name: "Puerto Carreño", code: "PCR", country: "Colombia" },
  { name: "Lima", code: "LIM", country: "Perú" },
  { name: "Ciudad de México", code: "MEX", country: "México" },
  { name: "Miami", code: "MIA", country: "Estados Unidos" },
  { name: "Madrid", code: "MAD", country: "España" },
  { name: "Nueva York", code: "JFK", country: "Estados Unidos" },
  { name: "París", code: "CDG", country: "Francia" },
  { name: "Barcelona", code: "BCN", country: "España" },
  { name: "Londres", code: "LHR", country: "Reino Unido" },
  { name: "Roma", code: "FCO", country: "Italia" },
  { name: "Ámsterdam", code: "AMS", country: "Países Bajos" },
  { name: "Tokio", code: "NRT", country: "Japón" },
  { name: "Sídney", code: "SYD", country: "Australia" },
  { name: "Toronto", code: "YYZ", country: "Canadá" },
  { name: "Buenos Aires", code: "EZE", country: "Argentina" },
  { name: "Santiago", code: "SCL", country: "Chile" },
  { name: "Aruba", code: "AUA", country: "Aruba" },
  { name: "Asunción", code: "ASU", country: "Paraguay" },
  { name: "Baltra, Galápagos", code: "GPS", country: "Ecuador" },
  { name: "Boston", code: "BOS", country: "Estados Unidos" },
]

export const otherPopularDestinations: Location[] = [
  { name: "Cancún", code: "CUN", country: "México" },
  { name: "Punta Cana", code: "PUJ", country: "República Dominicana" },
  { name: "São Paulo", code: "GRU", country: "Brasil" },
  { name: "Río de Janeiro", code: "GIG", country: "Brasil" },
  { name: "Los Ángeles", code: "LAX", country: "Estados Unidos" },
  { name: "Orlando", code: "MCO", country: "Estados Unidos" },
  { name: "Quito", code: "UIO", country: "Ecuador" },
  { name: "Guayaquil", code: "GYE", country: "Ecuador" },
];

export const promotions: Promotion[] = [
  {
    id: "promo1",
    title: "Escapada a Cartagena",
    description: "Disfruta de las playas y la historia colonial con un 30% de descuento",
    origin: "BOG",
    destination: "CTG",
    price: 299000,
    imageUrl: "/cartagena.jpg",
    validUntil: "2025-06-30",
  },
  {
    id: "promo2",
    title: "Aventura en San Andrés",
    description: "Conoce el mar de los 7 colores con tarifas especiales",
    origin: "BOG",
    destination: "ADZ",
    price: 399000,
    imageUrl: "sanAndres.jpg",
    validUntil: "2025-07-15",
  },
  {
    id: "promo3",
    title: "Descubre Madrid",
    description: "Vuelos directos a la capital española desde $1.599.000",
    origin: "BOG",
    destination: "MAD",
    price: 1599000,
    imageUrl: "madrid.webp",
    validUntil: "2025-08-31",
  },
  {
    id: "promo4",
    title: "Escapada a Miami",
    description: "Compras y playa en un solo destino con precios especiales",
    origin: "BOG",
    destination: "MIA",
    price: 899000,
    imageUrl: "miami.jpg",
    validUntil: "2025-09-15",
  },
]

export const services = [
  {
    id: "service1",
    title: "Equipaje adicional",
    description: "Viaja con todo lo que necesitas añadiendo maletas extra a tu reserva",
    icon: "Luggage",
    link: "/equipaje-adicional",
  },
  {
    id: "service2",
    title: "Selección de asientos",
    description: "Elige tu asiento preferido y viaja más cómodo",
    icon: "Armchair",
    link: "/seleccion-asientos",
  },
  {
    id: "service3",
    title: "Seguro de viaje",
    description: "Protege tu viaje contra imprevistos y emergencias médicas",
    icon: "Shield",
    link: "/seguro-viaje",
  },
  {
    id: "service4",
    title: "Alquiler de autos",
    description: "Reserva un auto y recógelo al llegar a tu destino",
    icon: "Car",
    link: "https://www.rentalcars.com/?affiliateCode=avianca695&adplat=cardlandingpage",
  },
]
